### ISSUE TITLE
Hot to get the local affine information matrix Ai in your Section 4.2?

### ISSUE THREAD

**Issue by ZeroSteven618** [sailor-z/NM-Net#10]
Excuse me, I wonder a question in your neighbor mining part.
In the **Section 4.2** in your paper:
You picked the local affine information matrix as a **2*2 matrix A** to build the matrix **T**.
But I do not know how to get the matrix A, the non-singular matrix.

How to get the 4 elements of the A matrix?
I searched the original paper:  **Scale & affine invariant interest point detectors** and found the similar description as
![Source](https://user-images.githubusercontent.com/66064813/100301777-dc909580-2fd3-11eb-9d1b-98af8a7b3da1.png)

Is there any available code in OpenCV to build the A matrix?
Or where is your implementation of the A matrix in your code? 
I could not find it. Sorry for bothering you with this.

**Comment by sailor-z** [comment]
Hi,
Please refer to https://github.com/sailor-z/NM-Net/blob/0cdfa6a71a1504d77c0798fe1cf0611d52ba2378/code/hessian.m#L13
