### ISSUE TITLE
missing colmap file

### ISSUE THREAD

**Issue by fantuslk** [sailor-z/NM-Net#2]
datasets/ has no COLMAP/train code，please check。

**Comment by sailor-z** [comment]
Thanks for the question. I'm sorry I'm not sure what's your meaning. The gerrard, graham, person, and south are four scences in COLMAP dataset.

**Comment by fantuslk** [comment]
Run train error:
FileNotFoundError:[Reeor 2]No such file or directory:'../datasets/COLMAP/train/xs.pkl'

**Comment by sailor-z** [comment]
Please follow the instructions of readme. Set 'initialize' to be True when
running 'main.py' at the first time.

fantuslk <notifications@github.com> 于 2019年7月21日周日 下午11:23写道：
