### ISSUE TITLE
About the code for GLR-Net

### ISSUE THREAD

**Issue by brandon9838** [sailor-z/NM-Net#8]
Hi, It's been a while and I wonder when the code for GLR-Net will be released.
I apologize for posting in the issue section of NM-Net, but I can't find your contact information anywhere on the page.
Thanks for replying!

**Comment by sailor-z** [comment]
Hi,
Sorry for the late reply. The code has been released at https://github.com/sailor-z/LGR-Net. Plese cite our paper if the code is useful.
Thanks.
